"""add user-country relationship and task_runs table

Revision ID: a14513afde2b
Revises: 2e7a391e0c8e
Create Date: 2025-11-28 18:14:17.749513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a14513afde2b'
down_revision = '2e7a391e0c8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferred_countries',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('country_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'country_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preferred_countries')
    # ### end Alembic commands ###
